first_blog/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    path('category/<int:pk>', views.category, name='category'),
]

first_blog/comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/post/<int:post_pk>', views.post_comment, name='post_comment'),
]

first_blog/first_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

first_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

class Post(models.Model):
    """
    """
    title = models.CharField(max_length=70)  # 标题
    body = models.TextField()   # 正文
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，blank=True 可以允许空值
    excerpt = models.CharField(max_length=200, blank=True)

    # 一对多, 外键，一个文章只有一个分类， 但一个分类可以用于多个文章
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    # 多对多, 一个文章可以有多个标签，一个标签页可以用于多篇文章
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

first_blog/comments/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

first_blog/comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

first_blog/blog/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from comments.forms import CommentForm
from .models import Post, Category
# Create your views here.

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', context={'post_list': post_list})

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body, 
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
    form = CommentForm()
    comment_list = post.comment_set.all()

    context = {
        'post': post,
        'form': form,
        'comment_list': comment_list
    }
    return render(request, 'blog/detail.html', context=context)

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})

first_blog/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import Comment
from .forms import CommentForm
# Create your views here.

def post_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            context = {
                'post': post,
                'form': form,
                'comment_list': comment_list
            }
            return render(request, 'blog/detail.html', context=context)
    return redirect(post)

first_blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    {% load static %}
    {% load blog_tags %}
    <link rel="stylesheet" href="{% static 'blog/highlights/default.css' %}">
</head>
<body>
    <nav class="nav">
        <h1>
            <a href="{% url 'blog:index' %}">Home</a>
        </h1>
    </nav>
    <section class="recent-post">
        <h3 class="siderbar-title">最新文章</h3>
        {% get_recent_posts as recent_post_list  %}
        <ul>
            {% for post in recent_post_list %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% empty %}
                暂无文章!
            {% endfor %}
        </ul>
    </section>
    <section class="post-archives">
        <h3 class="siderbar-title">文章归档</h3>
        {% archives as date_list %}
        <ul>
            {% for date in date_list %}
                <li>
                    <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                </li>
            {% empty %}
                暂无归档!
            {% endfor %}
        </ul>
    </section>
    <section class="post-category">
        <h3 class="siderbar-title">文章分类</h3>
        {% get_categories as category_list %}
        <ul>
            {% for category in category_list %}
                <li>
                    <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.post_set.count }})</span></a>
                </li>
            {% empty %}
                暂无分类!
            {% endfor %}
        </ul>
    </section>
    {% block main %}
    {% endblock main %}

    {% block toc %}
    {% endblock toc %}
</body>
</html>

first_blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block main %}
    <article class="post">
        <header class="post-header">
            <h1 class="post-title">
                {{ post.title }}
            </h1>
            <div class="post-meta">
                <span class="post-category">
                    <a href="#">{{ post.category.name }}</a>
                </span>
                <span class="post-date">
                    <a href="#">
                        <time datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                    </a>
                </span>
                <span class="post-author">
                    <a href="#">{{ post.author }}</a>
                </span>
                <span class="comments">
                    <a href="#">评论</a>
                </span>
                <span class="views-count">
                    <a href="#">588 阅读</a>
                </span>
            </div>
        </header>
        <div class="post content">
                {{ post.body | safe }}
        </div>
    </article>
    <section id="comment-area">
        <h3>
            评论列表
        </h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <label for="{{ form.name.id_for_label }}">名字：</label>
            {{ form.name }}
            {{ form.name.errors }}

            <label for="{{ form.email.id_for_label }}">邮箱：</label>
            {{ form.email }}
            {{ form.email.errors }}

            <label for="{{ form.url.id_for_label }}">URL：</label>
            {{ form.url }}
            {{ form.url.errors }}

            <label for="{{ form.text.id_for_label }}">评论：</label>
            {{ form.text }}
            {{ form.text.errors }}

            <button type="submit" class="comment-btn">发表</button>
        </form>

        <ul class="comment-list">
            {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="comment-author">{{ comment.name }}</span>
                    <time class="comment-date">{{ comment.created_time }}</time>
                    <div class="comment-text">
                        {{ comment.text }}
                    </div>
                </li>
            {% empty %}
                暂无评论!
            {% endfor %}
        </ul>
    </section>
{% endblock main %}
{% block toc %}

{% endblock toc %}

first_blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}
    <h1>{{ welcome }}</h1>
    {% for post in post_list %}
        <article>
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category">
                    <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }} </a>
                </span>
                <span class="post-date">{{ post.created_time }} </span>
                <span class="post-author">{{ post.author }} </span>
                <span class="comments">
                    <a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a>
                </span>
                <span class="views-count">588 阅读</span>
            </div>
            <div class="entry-content">
                <p>{{ post.excerpt }}</p>
                <a href="{{ post.get_absolute_url }}" class="read-more">继续阅读</a>
            </div>
        </article>
    {% empty %}
        <div>暂时还没有发布文章！</div>
    {% endfor %}
{% endblock main %}